# ============================================================
# Oracle Cloud - Autonomous Database con Wallet
# Usado cuando corre en Docker/EC2
# El Wallet se copia dentro de la imagen Docker en /app/wallet
# ============================================================
spring.datasource.url=jdbc:oracle:thin:@dsy2206_tp?TNS_ADMIN=/app/wallet
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=EMILIA
spring.datasource.password=Password123!

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ============================================================
# AWS S3
# ============================================================
aws.s3.bucket=${AWS_S3_BUCKET:sistema-inscripcion-bucket}
aws.region=${AWS_REGION:us-east-1}
